name: GRI Gap Analysis

on:
  schedule:
    - cron: "30 7 1 * *"   # أول يوم في الشهر الساعة 07:30 UTC
  workflow_dispatch:

jobs:
  gap-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run gap analysis
        run: python scripts/gap_analysis.py

      - name: Upload gap results
        uses: actions/upload-artifact@v4
        with:
          name: gaps
          path: output/gaps/
